version: '3'
services:
  golang:
    restart: always
    build: .
    ports:
      - 8080:80
    volumes:
      - ./:/code
      
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
volumes:
 mongodb: